(*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*)

let fib_sum limit =
    let rec go i j acc =
        if (i > limit) then acc else
            if (i mod 2 = 0) then
                go j (i+j) (acc+i)
            else
                go j (i+j) acc
    in go 1 2 0

let () =
    Printf.printf "%d\n" (fib_sum 4_000_000)
